Update cron-test.yml

diff --git a/.github/workflows/cron-test.yml b/.github/workflows/cron-test.yml
--- a/.github/workflows/cron-test.yml
+++ b/.github/workflows/cron-test.yml
@@ -6,6 +6,8 @@ on:
 jobs:
   build_and_check:
     runs-on: ubuntu-latest
+    timeout-minutes: 60
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
@@ -13,6 +15,25 @@ jobs:
       - name: Install Broken Link Checker
         run: npm install -g broken-link-checker
 
-      - name: Run Cron Job
-        run: blc http://206.12.88.113/ -f --filter-level=3
-        timeout-minutes: 50
+      - name: Retry Run Cron Job
+        id: retry
+        run: |
+          retries=5
+          wait_seconds=10
+          success=false
+
+          for attempt in $(seq 1 $retries); do
+            echo "Running attempt $attempt"
+            timeout 1m blc http://206.12.88.113/ -f --filter-level=3 && success=true && break
+            echo "Job failed. Retrying in $wait_seconds seconds..."
+            sleep $wait_seconds
+          done
+
+          if [ "$success" = true ]; then
+            echo "Link checker finished successfully."
+            # Custom actions for successful completion
+          else
+            echo "Link checker failed after $retries attempts."
+            # Custom actions for failure
+            exit 1
+          fi
